### ISSUE TITLE
surgeprotector.py

### ISSUE THREAD

**Issue by boldsuck** [artikel10/surgeprotector#1]
Hi Alex;

I don't quite understand line 87-88.
https://github.com/artikel10/surgeprotector/blob/8d9e6f4c087d6c58a4d334d5c218761efac4cce9/surgeprotector.py#L87
Is that supposed to find IPv6 addresses?
Then **reject6** should be in line 88
https://github.com/artikel10/surgeprotector/blob/8d9e6f4c087d6c58a4d334d5c218761efac4cce9/surgeprotector.py#L88
`line = f'ExitPolicy reject6 [{addr}] # {timestamp}\n'`

**Comment by alxndr42** [comment]
@boldsuck The `reject` keyword should work with IPv4 and IPv6 addresses. The check is there to make sure that IPv6 addresses appear in square brackets.

**Comment by boldsuck** [comment]
OK, thanks. I always use accept6 and reject6 for IPv6 in exit policy.

But you're right `man torrc` says:
`accept6 and reject6 only produce IPv6 exit policy entries. Using an IPv4 address with accept6 or reject6 is ignored and generates a warning. accept/reject allows either IPv4 or IPv6 addresses.`
